name: Build APK Bianca Beauty

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar dependências do sistema
      run: |
        Use Python 3.11 to fix Cython compatibility issue

    - name: Limpar cache do Buildozer
      run: rm -rf .buildozer

    - name: Compilar APK com Buildozer
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: BiancaBeauty-APK
        path: bin/*.apk
